name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: "vendortest.yaml"
        repository-append: "https://packages.wolfi.dev/os"
        keyring-append: "https://packages.wolfi.dev/os/wolfi-signing.rsa.pub"
        repository-path: ${{ github.workspace }}/packages/vendortest
    - run: find ${{ github.workspace }}/packages/vendortest